# Generated by Django 4.1.7 on 2023-03-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_details',
            name='category',
            field=models.CharField(default='General', max_length=250),
        ),
    ]
